kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cn.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cn.fullname" . }}
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
