{{- if not .Values.connector.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cn.fullname" . }}
  labels:
{{ include "cn.labels" . | indent 4 }}
{{- if .Values.additionalLabels -}}
  {{- toYaml .Values.additionalLabels | nindent 4 }}
{{- end }}
type: Opaque
data:
  TG_API_KEY: "{{ required "API Key required" .Values.twingate.apiKey | b64enc }}"
{{- end -}}
